"""add relationship

Revision ID: 2af7557a0ba5
Revises: f297bdab79a3
Create Date: 2022-05-20 00:16:49.354641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2af7557a0ba5'
down_revision = 'f297bdab79a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_details', sa.Column('person', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_details', 'user', ['person'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_details', type_='foreignkey')
    op.drop_column('user_details', 'person')
    # ### end Alembic commands ###
