"""add relationship

Revision ID: be20af19cd40
Revises: 2af7557a0ba5
Create Date: 2022-05-20 05:31:12.746044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be20af19cd40'
down_revision = '2af7557a0ba5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_details', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_details', 'user', ['user_id'], ['id'])
    op.drop_column('user_details', 'person')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_details', sa.Column('person', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'user_details', type_='foreignkey')
    op.drop_column('user_details', 'user_id')
    # ### end Alembic commands ###
